language: go
sudo: false
go:
  - "1.x"

script:
  - cd $HOME/gopath/src/github.com/miekg/exdns/q; go build
  - cd $HOME/gopath/src/github.com/miekg/exdns/as112; go build
  - cd $HOME/gopath/src/github.com/miekg/exdns/chaos; go build
  - cd $HOME/gopath/src/github.com/miekg/exdns/check-soa; go build
  - cd $HOME/gopath/src/github.com/miekg/exdns/reflect; go build
